export interface StreamSource {
  id: string;
  name: string;
  codename: string;
  quality: string;
  ping: string;
  type: string;
  isEmbed: boolean;
  getMovieUrl: (tmdbId: string | number, imdbId?: string) => string;
  getTvUrl: (tmdbId: string | number, season: number, episode: number, imdbId?: string) => string;
}

export const STREAM_SOURCES: StreamSource[] = [
  {
    id: 'vidlink',
    name: 'VidLink',
    codename: 'Lula',
    quality: '1080p',
    ping: '18ms',
    type: 'Multi-Server Fast',
    isEmbed: true,
    getMovieUrl: (id) => `https://vidlink.pro/movie/${id}`,
    getTvUrl: (id, s, e) => `https://vidlink.pro/tv/${id}/${s}/${e}`,
  },
  {
    id: 'vidsrc-to',
    name: 'VidSrc.to',
    codename: 'Sara',
    quality: '4K',
    ping: '24ms',
    type: 'Ultra HD Direct',
    isEmbed: true,
    getMovieUrl: (id) => `https://vidsrc.to/embed/movie/${id}`,
    getTvUrl: (id, s, e) => `https://vidsrc.to/embed/tv/${id}/${s}/${e}`,
  },
  {
    id: 'autoembed',
    name: 'AutoEmbed',
    codename: 'Elsie',
    quality: '1080p',
    ping: '15ms',
    type: 'Auto Fallback CDN',
    isEmbed: true,
    getMovieUrl: (id) => `https://player.autoembed.cc/embed/movie/${id}`,
    getTvUrl: (id, s, e) => `https://player.autoembed.cc/embed/tv/${id}/${s}/${e}`,
  },
  {
    id: 'embedsu',
    name: 'Embed.su',
    codename: 'Iris',
    quality: '1080p',
    ping: '21ms',
    type: 'Fast Multi-Stream',
    isEmbed: true,
    getMovieUrl: (id) => `https://embed.su/embed/movie/${id}`,
    getTvUrl: (id, s, e) => `https://embed.su/embed/tv/${id}/${s}/${e}`,
  },
  {
    id: 'vidsrc-cc',
    name: 'VidSrc CC',
    codename: 'Cary',
    quality: '1080p',
    ping: '28ms',
    type: 'Dual-Audio Mirror',
    isEmbed: true,
    getMovieUrl: (id) => `https://vidsrc.cc/v2/embed/movie/${id}`,
    getTvUrl: (id, s, e) => `https://vidsrc.cc/v2/embed/tv/${id}/${s}/${e}`,
  },
  {
    id: 'vidsrc-me',
    name: 'VidSrc.me',
    codename: 'Perla',
    quality: '1080p',
    ping: '31ms',
    type: 'Classic Mirror',
    isEmbed: true,
    getMovieUrl: (id) => `https://vidsrc.me/embed/movie?tmdb=${id}`,
    getTvUrl: (id, s, e) => `https://vidsrc.me/embed/tv?tmdb=${id}&sea=${s}&epi=${e}`,
  },
  {
    id: 'vidsrc-icu',
    name: 'VidSrc ICU',
    codename: 'Kaya',
    quality: '1080p',
    ping: '25ms',
    type: 'Ultra Mirror',
    isEmbed: true,
    getMovieUrl: (id) => `https://vidsrc.icu/embed/movie/${id}`,
    getTvUrl: (id, s, e) => `https://vidsrc.icu/embed/tv/${id}/${s}/${e}`,
  },
  {
    id: 'vidsrc-vip',
    name: 'VidSrc VIP',
    codename: 'Mira',
    quality: '1080p',
    ping: '29ms',
    type: 'VIP Server',
    isEmbed: true,
    getMovieUrl: (id) => `https://vidsrc.vip/embed/movie/${id}`,
    getTvUrl: (id, s, e) => `https://vidsrc.vip/embed/tv/${id}/${s}/${e}`,
  },
  {
    id: 'twoembed',
    name: '2Embed',
    codename: 'Talia',
    quality: '720p',
    ping: '45ms',
    type: 'Multi-Language Mirror',
    isEmbed: true,
    getMovieUrl: (id) => `https://www.2embed.cc/embed/${id}`,
    getTvUrl: (id, s, e) => `https://www.2embed.cc/embedtv/${id}&s=${s}&e=${e}`,
  },
  {
    id: 'multiembed',
    name: 'MultiEmbed',
    codename: 'Mona',
    quality: '1080p',
    ping: '26ms',
    type: 'Global Mirror Network',
    isEmbed: true,
    getMovieUrl: (id) => `https://multiembed.mov/?video_id=${id}&tmdb=1`,
    getTvUrl: (id, s, e) => `https://multiembed.mov/?video_id=${id}&tmdb=1&s=${s}&e=${e}`,
  },
  {
    id: 'smashystream',
    name: 'SmashyStream',
    codename: 'Zola',
    quality: '1080p',
    ping: '38ms',
    type: 'High Speed CDN',
    isEmbed: true,
    getMovieUrl: (id) => `https://embed.smashystream.com/playere.php?tmdb=${id}`,
    getTvUrl: (id, s, e) => `https://embed.smashystream.com/playere.php?tmdb=${id}&season=${s}&episode=${e}`,
  },
  {
    id: 'moviesapi',
    name: 'MoviesAPI',
    codename: 'Nova',
    quality: '1080p',
    ping: '22ms',
    type: 'High Bitrate Club',
    isEmbed: true,
    getMovieUrl: (id) => `https://moviesapi.club/movie/${id}`,
    getTvUrl: (id, s, e) => `https://moviesapi.club/tv/${id}-${s}-${e}`,
  },
  {
    id: 'rive',
    name: 'Rive Stream',
    codename: 'Rhea',
    quality: '1080p',
    ping: '20ms',
    type: 'Zero-Buffering Stream',
    isEmbed: true,
    getMovieUrl: (id) => `https://rive.stream/embed?type=movie&id=${id}`,
    getTvUrl: (id, s, e) => `https://rive.stream/embed?type=tv&id=${id}&season=${s}&episode=${e}`,
  },
  {
    id: 'vixsrc',
    name: 'VixSrc',
    codename: 'Vera',
    quality: '1080p',
    ping: '29ms',
    type: 'Clean Feed',
    isEmbed: true,
    getMovieUrl: (id) => `https://vidsrc.in/embed/movie/${id}`,
    getTvUrl: (id, s, e) => `https://vidsrc.in/embed/tv/${id}/${s}/${e}`,
  },
  {
    id: 'frembed',
    name: 'FrEmbed',
    codename: 'Faye',
    quality: '1080p',
    ping: '33ms',
    type: 'European Mirror',
    isEmbed: true,
    getMovieUrl: (id) => `https://frembed.live/api/film.php?id=${id}`,
    getTvUrl: (id, s, e) => `https://frembed.live/api/serie.php?id=${id}&sa=${s}&ea=${e}`,
  },
  {
    id: 'nontongo',
    name: 'NontonGo',
    codename: 'Nila',
    quality: '1080p',
    ping: '37ms',
    type: 'Asia-Pacific Mirror',
    isEmbed: true,
    getMovieUrl: (id) => `https://www.nontongo.win/embed/movie/${id}`,
    getTvUrl: (id, s, e) => `https://www.nontongo.win/embed/tv/${id}/${s}/${e}`,
  },
  {
    id: 'aniwave',
    name: 'AniEmbed',
    codename: 'Aiko',
    quality: '1080p',
    ping: '16ms',
    type: 'Dedicated Anime Stream',
    isEmbed: true,
    getMovieUrl: (id) => `https://anime.autoembed.cc/embed/${id}`,
    getTvUrl: (id, s, e) => `https://anime.autoembed.cc/embed/${id}/${s}/${e}`,
  },
  {
    id: 'vidnest',
    name: 'VidNest',
    codename: 'Nora',
    quality: '1080p',
    ping: '35ms',
    type: 'High Availability',
    isEmbed: true,
    getMovieUrl: (id) => `https://vidlink.pro/movie/${id}`,
    getTvUrl: (id, s, e) => `https://vidlink.pro/tv/${id}/${s}/${e}`,
  },
  {
    id: 'native',
    name: 'Native Player Engine',
    codename: 'Kerasoni Core',
    quality: '1080p',
    ping: '10ms',
    type: 'Custom Controls & Subtitles',
    isEmbed: false,
    getMovieUrl: () => '',
    getTvUrl: () => '',
  }
];
